PUSH DWORD 0 ; Dim i as INTEGER [EBP−4]
PUSH DWORD 0 ; Dim n as INTEGER [EBP−8]
PUSH DWORD 0 ; Dim f as INTEGER [EBP−12]
MOV EBX, 5
MOV [EBP - 8], EBX ; n = 5
MOV EBX, 2
MOV [EBP - 4], EBX ; i = 2
MOV EBX, 1
MOV [EBP - 12], EBX ; f = 1
LOOP_33:
MOV EBX, [EBP - 4]
PUSH EBX
MOV EBX, [EBP - 8]
PUSH EBX
MOV EBX, 1
POP EAX
ADD EAX, EBX
MOV EBX, EAX
POP EAX
CMP EAX, EBX
CALL binop_jg
CMP EBX, False
JE EXIT_33
MOV EBX, [EBP - 12]
PUSH EBX
MOV EBX, [EBP - 4]
POP EAX
IMUL EBX
MOV EBX, EAX
MOV [EBP - 12], EBX ; f = 2
MOV EBX, [EBP - 4]
PUSH EBX
MOV EBX, 1
POP EAX
ADD EAX, EBX
MOV EBX, EAX
MOV [EBP - 4], EBX ; i = 3
JMP LOOP_33
EXIT33:
MOV EBX, [EBP - 12]
PUSH EBX
CALL print
POP EBX
